install script fixed

diff --git a/install b/install
--- a/install
+++ b/install
@@ -22,27 +22,27 @@ declare -A host_ip
 # 	qui n'expose pas les données collectés par les differents services.
 #
 # Configuration:
-ARCH=${ARCH:="arm64"}
-OS=${OS:="linux"}
-DISTRO=${DISTRO:="debian"}
-WINDOWS_ARCH=${WINDOWS_ARCH:="amd64"}
-MACOS_ARCH=${MACOS_ARCH:="arm64"}
-PKG_MANAGER=${PKG_MANAGER:="apt"}
+ARCH=${ARCH:=arm64}
+OS=${OS:=linux}
+DISTRO=${DISTRO:=debian}
+WINDOWS_ARCH=${WINDOWS_ARCHamd64}
+MACOS_ARCH=${MACOS_ARCH:=arm64}
+PKG_MANAGER=${PKG_MANAGER:=apt}
 
 packages=(
-	["zabbix"]				="${ZABBIX_VERSION:="7.0"}"			#LTS
-	["prometheus"]			="${PROMETHEUS_VERSION:="2.54.1"}"	#2024-08-27
-	["node_exporter"]		="${NODEEXP_VERSION:="1.8.2"}"		#2024-06-19
-	["windows_exporter"]	="${WINDOWSEXP_VERSION:="0.28.1"}"	#2024-08-31
-	["grafana"]				="${GRAFANA_VERSION:=""}"				#
-	["elasticsearch"]		="${ELASTIC_VERSION:=""}"				#
-	["kibana"]				="${KIBANA_VERSION:=""}"				#
-	["metricbeat"]			="${METRIC_VERSION:=""}"				#
-	["logstash"]			="${LOGSTASH_VERSION:=""}"			#
-	["thehive"]				="${THEHIVE_VERSION:=""}"				#
-	["mariadb"]				="${MARIADB_VERSION:=""}"				#
-	["nginx"]				="${NGINX_VERSION:=""}"				#
-	["MISP"]				="${MISP_VERSION:=""}"				#
+	["zabbix"]="${ZABBIX_VERSION:=7.0}"						#LTS
+	["prometheus"]="${PROMETHEUS_VERSION:=2.54.1}"			#2024-08-27
+	["node_exporter"]="${NODEEXP_VERSION:=1.8.2}"			#2024-06-19
+	["windows_exporter"]="${WINDOWSEXP_VERSION:=0.28.1}"	#2024-08-31
+	["grafana"]="${GRAFANA_VERSION:=}"						#
+	["elasticsearch"]="${ELASTIC_VERSION:=}"				#
+	["kibana"]="${KIBANA_VERSION:=}"						#
+	["metricbeat"]="${METRIC_VERSION:=}"					#
+	["logstash"]="${LOGSTASH_VERSION:=}"					#
+	["thehive"]="${THEHIVE_VERSION:=}"						#
+	["mariadb"]="${MARIADB_VERSION:=}"						#
+	["nginx"]="${NGINX_VERSION:=}"							#
+	["MISP"]="${MISP_VERSION:=}"							#
 )
 
 # Fin de la configuration
@@ -51,19 +51,42 @@ packages=(
 #
 unset VERSION
 unset version
-if ! [ -e "$(which dialog)" ]; then echo "should install dialog to use this script.\n\t wanna do it now ? [Yy/Nn] "; read -n1 dialog_install;
-	if [ "$install_dialog" = "Y" ] || [ "$install_dialog" = "y" ]; then
-		$PKG_MANAGER install -y dialog
+if [[ "$(uname -o)" =~ "[Ll]inux"* ]]; then
+	if ! [ -e "$(which ip)" ]; then
+		echo "ip utility is required to run this script."
+		exit 1
+	fi
+	ip="ip"
+elif [[ "$(uname)" =~ "Darwin" ]] ; then
+	if ! [ -e "$(which ifconfig)" ]; then
+		echo "ifconfig utility is required to run this script."
+		exit 1
+	fi
+	ip="ifconfig"
+else
+	echo "your OS isn't supported currently. exiting."
+	exit 1
+fi
+if ! [ -e "$(which dialog)" ]; then
+	echo "Should install dialog to use this script.\n\t wanna do it now ? [Yy/Nn] ";
+	read -n1 dialog_install;
+	if [[ "$install_dialog" = "[yY]" ]] ; then
+		"${PKG_MANAGER}" install -y dialog
 		if [ "$?" = "0" ]; then
 			echo "${PKG_MANAGER} encountered an error.";
+			exit 1
 		fi
 	fi
 fi
-
-host_ip=($(ip a | grep inet | awk '{print $2}' | tr "\n" " "))
+if [ "${ip}" = "ip" ]; then
+	host_ip=($(ip a | grep inet | awk '{print $2}' | tr "\n" " "))
+elif [ "${ip}" = "ifconfig" ]; then
+	host_ip=($(ifconfig a | grep inet | awk '{print $2}' | tr "\n" " "))
+fi
 gh_prometheus="https://github.com/prometheus/"
 gh_prometheus_community="https://github.com/prometheus-community/"
-
+echo "${ip}"
+echo "${host_ip}"
 get_installer() {
 	local version=$1
 	local package=$2
@@ -102,7 +125,7 @@ make_unit() {
 	service_group=$3
 	description=$4
 	binary=$5
-	cat <<EOF>"/etc/systemd/system/$1.service"
+	cat <<EOF >"/etc/systemd/system/$1.service"
 [Unit]
 Description=Prometheus Monitoring
 Wants=network-online.target
@@ -121,6 +144,7 @@ ExecStart=/usr/local/bin/prometheus \
 [Install]
 WantedBy=multi-user.target
 EOF
+
 }
 
 print_help() {
@@ -143,6 +167,6 @@ print_help() {
 #	((i++))
 #done
 
-select ip in ${host_ip[@]}; do
-	echo $ip
-done
+#select ip in ${host_ip[@]}; do
+#	echo $ip
+#done
